version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: localhost
    environment:
      - AXONIQ_AXONSERVER_STANDALONE=true
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'